---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
acled %>% glimpse()
```

### sub-event types

```{r}
acled %>% filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  filter(!str_detect(notes, "PDF|pdf")) %>% 
  sample_n(10) %>% 
  pull(notes)

  count(sub_event_type)

acled %>% filter(year == 2021) %>% 
  filter(sub_event_type == "Remote explosive/landmine/IED") %>% 
  sample_n(10) %>% 
  pull(notes)

acled %>% filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  filter(str_detect(notes, "plant")) %>% 
  sample_n(10) %>% 
  pull(notes)

acled %>% filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  filter(non_combatant == 1)
  mutate(civ_involved = ifelse(str_detect(notes, "PDF|military"), "military", "civilian")) %>%
  filter(civ_involved == "civilian")

acled %>% filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  filter(str_detect(notes, "military")) %>% 
  sample_n(10) %>% 
  pull(notes)


acled %>% filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  mutate(civ_involved = case_when(str_detect(notes, "civilian") ~ "civilian",
                                  str_detect(notes, "PDF|military|Military|convoy|troop") ~ "military", 
                                  TRUE ~ "civilian")) %>% 
  # mutate(civ_involved = ifelse(str_detect(notes, "PDF|military"), "military", "civilian")) %>%
  filter(civ_involved == "civilian") %>% 
  filter(str_detect(notes, "jet")) %>% pull(notes)
  sample_n(10) %>% 
  pull(notes)


  
```

### mine-action working group

```{r}
# creating civ_involved
acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  mutate(civ_involved = case_when(str_detect(actor1, "Civilian") ~ "yes",
                                  str_detect(actor2, "Civilian") ~ "yes",
                                  str_detect(notes, "civilian|villager|police|car|office|ward|Ward") ~ "yes",
                                  str_detect(notes, "PDF|Defense|convoy|troop|army|Army|military|Military") ~ "no",
                                  TRUE ~ "yes"), 
         non_military = fct_rev(civ_involved)) %>%
  filter(non_military == "yes") %>% 
  sample_n(10) %>% pull(notes)
```


```{r fig.height = 10}
# map 1
acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  mutate(civ_involved = case_when(str_detect(actor1, "Civilian") ~ "yes",
                                  str_detect(actor2, "Civilian") ~ "yes",
                                  str_detect(notes, "civilian|villager|police|car|office|ward|Ward") ~ "yes",
                                  str_detect(notes, "PDF|Defense|convoy|troop|army|Army|military|Military") ~ "no",
                                  TRUE ~ "yes"), 
         civ_involved = fct_rev(civ_involved)) %>%
  right_join(pcode3_shape, by = "admin3_pcode") %>% 
  filter(!is.na(civ_involved)) %>% 
  st_as_sf() %>% 
  ggplot() +
  geom_sf(alpha = 0, size = 0.1) + 
  geom_point(aes(x = longitude, y = latitude,  colour = civ_involved), alpha = 0.5, size = 0.7) +
  scale_colour_manual(values = c("red", "blue")) +
  # scale_size_continuous(range = c(0.5, 5)) +
  geom_sf(data = pcode1_shape, alpha = 0, colour = "black", size = 0.5) +
  theme_void() +
  labs(colour = "civilians\ninvolved", 
       title = "Incidents of explosions and remote violence (2021)", 
       caption = "Data source: ACLED; acleddata.com ") +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(plot.caption=element_text(hjust = 0.5),
        plot.background = element_rect(fill = "white", colour = NA))

ggsave(filename = "./sharing/explosions_remote_violence_map1.png", dpi = 300, height = 12, width = 7, units = "in")
```

```{r fig.height = 10}
# map 2
acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  mutate(civ_involved = case_when(str_detect(actor1, "Civilian") ~ "yes",
                                  str_detect(actor2, "Civilian") ~ "yes",
                                  str_detect(notes, "civilian|villager|police|car|office|ward|Ward") ~ "yes",
                                  str_detect(notes, "PDF|Defense|convoy|troop|army|Army|military|Military") ~ "no",
                                  TRUE ~ "yes"), 
         civ_involved = fct_rev(civ_involved)) %>%
  right_join(pcode3_shape, by = "admin3_pcode") %>% 
  filter(!is.na(civ_involved)) %>% 
  st_as_sf() %>% 
  ggplot() +
  geom_sf(alpha = 0, size = 0.1) + 
  geom_point(aes(x = longitude, y = latitude, size = fatalities, colour = civ_involved), alpha = 0.5) +
  scale_colour_manual(values = c("red", "blue")) +
  scale_size_continuous(range = c(1, 5)) +
  geom_sf(data = pcode1_shape, alpha = 0, colour = "black", size = 0.5) +
  theme_void() +
  labs(colour = "civilians\ninvolved", 
       title = "Incidents of explosions and remote violence (2021)",
       subtitle = "Size of each point indicates the number of fatalities", 
       caption = "Data source: ACLED; acleddata.com ") +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(plot.caption=element_text(hjust = 0.5),
        plot.background = element_rect(fill = "white", colour = NA))

ggsave(filename = "./sharing/explosions_remote_violence_map2.png", dpi = 300, height = 12, width = 7, units = "in")
```


```{r}
# kable 
acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  mutate(civ_involved = case_when(str_detect(actor1, "Civilian") ~ "yes",
                                  str_detect(actor2, "Civilian") ~ "yes",
                                  str_detect(notes, "civilian|villager|police|car|office|ward|Ward") ~ "yes",
                                  str_detect(notes, "PDF|Defense|convoy|troop|army|Army|military|Military") ~ "no",
                                  TRUE ~ "yes")) %>%
  group_by(sub_event_type, civ_involved) %>% 
  summarise(events = n(), 
            fatalities = sum(fatalities)) %>%
  rename(civilians_involved = civ_involved) %>% 
  arrange(desc(civilians_involved)) %>% 
  arrange(sub_event_type) %>%
  kable(caption = "Summary of incidents of explosions and remote violence", format.args = list(big.mark = ",")) %>% 
  kable_classic_2("striped", full_width = FALSE) %>% 
  footnote(general = "Data source: Armed Conflict Location & Event Data Project (ACLED); acleddata.com",
           general_title = "") %>%
  save_kable(file = "./sharing/summary_table.png", zoom = 2)


```


```{r}
acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  mutate(civ_involved = case_when(str_detect(actor1, "Civilian") ~ "yes",
                                  str_detect(actor2, "Civilian") ~ "yes",
                                  str_detect(notes, "civilian|villager|police|car|office|ward|Ward") ~ "yes",
                                  str_detect(notes, "PDF|Defense|convoy|troop|army|Army|military|Military") ~ "no",
                                  TRUE ~ "yes"), 
         non_military = fct_rev(civ_involved)) %>%
  select(-non_combatant) %>% 
  write_csv("./sharing/explosions_remote_violence.csv")
  
```



```{r}
acled %>% 
  filter(year == 2021) %>% 
  filter(str_detect(notes, "IED|remote")) %>% 
  pull(notes)

acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  count(sub_event_type)
  
acled %>% filter(year == 2021) %>% 
  filter(sub_event_type == "Remote explosive/landmine/IED" & str_detect(notes, "step")) %>% 
  sample_n(10) %>% 
  pull(notes)

acled %>% 
  filter(year == 2021) %>% 
  filter(sub_event_type == "Remote explosive/landmine/IED" | str_detect(notes, "mine")) %>% 
  sample_n(10) %>% 
  pull(notes)

```


### Agriculture

```{r}
# indicator guide for vulmmr
indicator_guide <- 
  read_excel("C:/Users/seany/Documents/R/mmr_5w_initial_observations/Datasets_Vulnerability_Analysis_in_Myanmar_09Jul2018 (1).xlsx",
           skip = 1) %>% 
  slice(1:3) %>% 
  janitor::clean_names() %>% 
  transpose_df() %>% 
  rename(indicator = rowname, 
         age_group = `1`,
         category = `2`, 
         source = `3`) %>% 
  slice(-1)

# reading in vulnerability dataset
vulmmr <- read_excel("C:/Users/seany/Documents/R/mmr_5w_initial_observations/Datasets_Vulnerability_Analysis_in_Myanmar_09Jul2018 (1).xlsx",
           skip = 1) %>% 
  slice(-c(1:3)) %>% 
  clean_names() %>% 
  select(-label) %>% 
  mutate_at(vars(number_of_village_tracts:wb_wealth_rank), as.numeric) %>% 
  mutate_at(vars(disasters_impacted_by_nargis_2008:acled_2015_2016_data_exists), as.logical) %>% 
  mutate_at(vars(conflict_2015_2016_number_of_battles:corrected_conflict_index_garry), as.numeric) %>% 
  select(-starts_with("x")) %>% 
  select(-c(private_sector_development_2014_2015, protection_2010_2015, shelter_2010_2015, wash_2010_2015))
```

```{r}
indicator_guide %>% count(category)

indicator_guide %>% filter(category == "Agriculture") %>% count(indicator)

vulmmr %>% 
  select(state_region_name, state_region_pcode, township_pcode, 
         contains("mali"), contains("sown_area"), all_harvested_net_margin_usd, sown_area_of_paddy_acres) %>% 
  mutate(pc_paddy = sown_area_of_paddy_acres / all_area_sowed_mali) %>% 
  arrange(desc(all_area_sowed_mali)) %>% 
  ggplot(aes(x = all_area_sowed_mali)) + 
  geom_histogram()
```


```{r}
ag_mali <- vulmmr %>% 
  select(state_region_name, state_region_pcode, township_pcode, 
         contains("mali"), contains("sown_area"), all_harvested_net_margin_usd, sown_area_of_paddy_acres) %>% 
  mutate(pc_paddy = sown_area_of_paddy_acres / all_area_sowed_mali) %>% 
  remove_empty() %>% 
  pivot_longer(cols = contains("sown_area"), names_to = "crop_type", values_to = "acres") %>%
  filter(crop_type != "sown_area_of_freen_gram_and_pegion_urad_pea_acres") %>% 
  mutate(acres = replace_na(acres, 0)) %>% 
  mutate(pc_total = acres / all_area_sowed_mali) %>% 
  mutate(crop_type = str_remove_all(crop_type, "sown_area_of_"),
         crop_type = str_remove_all(crop_type, "_acres"),
    crop_type = ifelse(crop_type %in% c("paddy", "sesame", "green_gram", 
                                        "urad_pea", "ground_nut", "pigeon_pea"),
                       crop_type, "other"), 
    crop_type = fct_relevel(crop_type, "other", after = Inf))


ag_ord <- ag_mali %>% 
  group_by(state_region_name) %>% 
  summarise(acres = sum(acres)) %>% 
  arrange(desc(acres)) %>%
  mutate(state_region_name = fct_reorder(state_region_name, acres)) %>% 
  pull(state_region_name) %>% 
  as_vector()

ag_mali %>% 
  group_by(state_region_name, crop_type) %>% 
  summarise(acres = sum(acres), .group = "drop") %>% 
  mutate(state_region_name = factor(state_region_name, 
                                         levels = c("Ayeyarwady", "Sagaing", "Bago", "Magway", "Mandalay", "Shan", "Yangon", "Rakhine",
                                                    "Kayin", "Mon", "Kachin", "Tanintharyi", "Kayah", "Chin", "Nay Pyi Taw")),
         state_region_name = fct_rev(state_region_name)) %>% 
  arrange(desc(acres)) %>% 
  ggplot(aes(x = state_region_name, y = acres, fill = crop_type)) + 
  geom_col() + 
  #scale_fill_viridis_d(option = "turbo") + 
  theme(axis.text.x = element_text(angle = 30, vjust = 0.7)) +
  labs(x = "",
       fill = "",
       title = "Number of acres sown by crop type")


  ggplot(aes(x = pc_total)) +
  geom_histogram()
  
```


```{r fig.height = 10}

acled %>% filter(year == 2021) %>%
  filter(event_type == "Explosions/Remote violence") %>%
  right_join(vulmmr %>%
               select(state_region_name, state_region_pcode, township_pcode,
                      contains("mali"), contains("sown_area"), 
                      all_harvested_net_margin_usd, sown_area_of_paddy_acres) %>%
               mutate(pc_paddy = sown_area_of_paddy_acres / all_area_sowed_mali), by = c("admin3_pcode" = "township_pcode")) %>% 
  right_join(pcode3_shape, by = "admin3_pcode") %>% 
  st_as_sf() %>% 
  ggplot() +
  geom_sf(aes(fill = all_area_sowed_mali), size = 0.1) + 
  geom_point(aes(x = longitude, y = latitude, size = fatalities), alpha = 0.5, colour = "red") +
  scale_colour_manual(values = c("red", "black")) +
  scale_size_continuous(range = c(0.3, 4)) +
  geom_sf(data = pcode1_shape, alpha = 0, colour = "black", size = 0.5) +
  scale_fill_viridis_c(direction = -1, label = scales::comma, breaks = c(0, 50000, 200000, 400000, 600000, 750000)) + 
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme_void() + 
  labs(fill = "sown area (acres)", 
       title = "Incidents of explosions and remote violence (2021) and agricultural area sown (2015)",
       caption = "Data source: ACLED; acleddata.com and Ministry of Agriculture and Irrigation") +
  theme(plot.caption=element_text(hjust = 0.2))

```

