---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidytext)
library(glmnet)
library(glmnetUtils)
library(broom)
library(rpart)
library(rattle)
library(stringi)
library(ggraph)
library(ggridges)
library(tidylo)

acled_words <- acled %>% 
  filter(year == 2021) %>% 
  select(data_id, notes) %>% 
  unnest_tokens(word, notes) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(str_detect(word, "[a-z]")) %>% 
  left_join(acled %>% 
              select(data_id, admin1, admin3_pcode, event_type, sub_event_type, fatalities, inter_type), by = "data_id")

```

```{r}
acled_conf_int <- acled %>%
  filter(year == 2021) %>%
  select(data_id, admin3_pcode, event_date, sub_event_type, event_type, fatalities, inter_type, notes) %>% 
  unnest_tokens(word, notes) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(str_detect(word, "[a-z]")) %>%
  add_count(word) %>% 
  filter(n > 50) %>% 
  nest(-word) %>% 
  mutate(model = map(data, ~ t.test(.$fatalities))) %>% 
  unnest_legacy(map(model, tidy)) %>%  
  mutate(word = fct_reorder(word, estimate))

acled_conf_int %>% arrange(desc(estimate))

acled_conf_int %>% 
  filter(word %out% c("fatality", "coded", "death", "village", "township", "district", "villages",
                      "town", "tract", "fatalities", "dvb", "aapp", "total", "irrawaddy", "rfa", "died",
                      "killing")) %>% 
  arrange(desc(estimate)) %>% 
  head(40) %>% 
  ggplot(aes(x = estimate, y = word)) +
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), size = 0.5) 

glimpse(acled)

```

```{r}
# to check specific entries 
acled %>% 
  filter(year == 2021) %>% 
  filter(str_detect(notes, "DVB"))

acled_conf_int %>% filter(word == "rfa") %>%
  select(data) %>% unnest()

acled %>% 
  filter(data_id == 7801674) %>% pull(notes)
```



```{r}


acled_words %>% 
  count(word, sort = TRUE) %>% 
  head(20) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(x = word, y = n)) + 
  geom_col() +
  coord_flip()
```

# pairwise correlations

```{r}

acled_words %>%  
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 50) %>% 
  pairwise_cor(word, data_id, sort = TRUE) %>%
  group_by(item1) %>% 
  top_n(correlation, n = 20) %>% 
  datatable(filter = list(position = "top", clear = FALSE), 
            options = list(pageLength = 10, scrollX = TRUE
  #                         
  #                         ,
  #                                         initComplete = htmlwidgets::JS(
  #        "function(settings, json) {",
  #        paste0("$(this.api().table().container()).css({'font-size': '", "8.5pt", "'});"),
  #        "}")
       ) 
     ) %>% 
  formatRound(c("correlation"), digits = 3)


```

### acled words filtered

```{r}

acled_words_filtered <- acled_words %>%  
  filter(word %out% c("fatality", "coded", "death", "village", "township", "district", "villages",
                      "town", "tract", "fatalities", "dvb", "aapp", "total", "irrawaddy", "rfa", "died",
                      "killing", "killed", "dead", "event", "events", "casualty", "casualties",
                      "size", "code", "report", "myanmar","coded")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 50)

# does it make sense to filter out peaceful protests? 
has_fatalities <- acled %>% 
  select(data_id, has_fatalities) %>% 
  inner_join(acled_words_filtered %>% select(data_id, word), by = "data_id") %>% 
  distinct()

fatalities <- acled %>% 
  select(data_id, fatalities) %>% 
  inner_join(acled_words_filtered %>% select(data_id, word), by = "data_id") %>% 
  distinct()

```
### network graph

```{r}
conflict_network_graph <- acled_words %>%  
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded",
                      "dvb", "aapp", "total", "irrawaddy", "rfa", "tract")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 70) %>% 
  pairwise_cor(word, data_id, sort = TRUE) %>% 
  filter(correlation >= 0.2) %>% 
  igraph::graph_from_data_frame() %>% 
  ggraph(layout = "fr") + 
  geom_edge_link(aes(alpha = correlation), colour = "blue") + 
  scale_alpha_continuous(range = c(0.1, 0.4)) +
  geom_node_point(colour = "blue", alpha = 0.3) +
  geom_node_text(aes(label = name), size = 2) + 
  theme(legend.position = "none") + 
  labs(title = "Network graph of words in 2021 conflict event descriptions in Myanmar",
       subtitle = "Data source: Armed Conflict Location & Event Data Project (ACLED); acleddata.com")

ggsave("conflict_network_graph.png", conflict_network_graph, width = 42.0, height = 29.7, units = "cm", dpi = 300)

```

```{r}
acled_words %>%  
  filter(fatalities > 0) %>% 
  # filter(event_type == "Battles") %>% 
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded",
                      "dvb", "aapp", "total", "irrawaddy", "rfa", "tract")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 70) %>% 
  pairwise_cor(word, data_id, sort = TRUE) %>% 
  filter(correlation >= 0.15) %>% 
  igraph::graph_from_data_frame() %>% 
  ggraph(layout = "fr") + 
  geom_edge_link(aes(alpha = correlation), colour = "blue") + 
  scale_alpha_continuous(range = c(0.1, 0.4)) +
  geom_node_point(colour = "blue", alpha = 0.3) +
  geom_node_text(aes(label = name), size = 2) + 
  theme(legend.position = "none") + 
  labs(title = "Network map of 2021 descriptions of conflict events in Myanmar with fatalities",
       subtitle = "Data source: Armed Conflict Location & Event Data Project (ACLED); acleddata.com")
  
  acled %>% count(event_type)
```



### glmnet models

```{r}
glmnet_model <- glmnet(has_fatalities ~ word, data = has_fatalities)

glmnet_model %>%
  tidy() %>% 
  mutate(term = str_remove_all(term, "word")) %>% 
  filter(term %in% c("accused", "convoy", "pale", "pdf")) %>% 
  ggplot(aes(x = lambda, y = estimate, colour = term)) + 
  geom_line() + 
  scale_x_log10() + 
  geom_hline(lty = 2, yintercept = 0)
```


```{r}
# how do we pick a lambda?
glmnet_model %>%
  tidy() %>% 
  mutate(term = str_remove_all(term, "word")) %>% 
  count(lambda) %>% 
  ggplot(aes(x = lambda, y = n)) + 
  geom_line() + 
  scale_x_log10()

```

```{r}
# cross-validated glmnet model
cv_glmnet_model_number <- cv.glmnet(fatalities ~ word, data = fatalities)

cv_glmnet_model_tf <- cv.glmnet(has_fatalities ~ word, data = has_fatalities)

plot(cv_glmnet_model_number)

cv_glmnet_model_tf$glmnet.fit %>% 
  tidy() %>% 
  mutate(term = str_remove_all(term, "word")) %>% 
  filter(lambda == cv_glmnet_model_tf$lambda.min & term != "(Intercept)") %>% 
  arrange(desc(estimate)) %>% 
  group_by(direction = ifelse(estimate < 0, "Negative", "Positive")) %>% 
  top_n(20, abs(estimate)) %>% 
  ungroup() %>%
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = term, y = estimate, fill = direction)) + 
  geom_col() + 
  coord_flip() 
```

```{r}
cv_glmnet_model_number$glmnet.fit %>% 
  tidy() %>% 
  mutate(term = str_remove_all(term, "word")) %>% 
  filter(lambda == cv_glmnet_model_number$lambda.min & term != "(Intercept)") %>% 
  arrange(desc(estimate)) %>% 
  group_by(direction = ifelse(estimate < 0, "Negative", "Positive")) %>% 
  top_n(20, abs(estimate)) %>% 
  ungroup() %>%
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = term, y = estimate, fill = direction)) + 
  geom_col() + 
  coord_flip()

acled %>% filter(year == 2021) %>% 
  filter(str_detect(notes, "informant")) %>% sample_n(10) %>% pull(notes) 
```

### in this instance, mod 2 is much less useful since it only goes note by note 
```{r}
# why don't we try this?

has_fatalities_matrix <- acled %>% 
  select(data_id, has_fatalities) %>% 
  right_join(acled_words_filtered %>% select(data_id, word, n), by = "data_id") %>% 
  distinct() %>% 
  cast_sparse(data_id, word, n)

y <- has_fatalities$has_fatalities[match(rownames(has_fatalities_matrix), has_fatalities$data_id)]

mod2 <- cv.glmnet(has_fatalities_matrix, y, family = "binomial")
```

```{r}
mod2$glmnet.fit %>% 
  tidy() %>% 
  filter(lambda == mod2$lambda.min & term != "(Intercept)") %>% 
  arrange(desc(estimate)) %>% 
  group_by(direction = ifelse(estimate < 0, "Negative", "Positive")) %>% 
  top_n(20, abs(estimate)) %>% 
  ungroup() %>%
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = term, y = estimate, fill = direction)) + 
  geom_col() + 
  coord_flip()

plot(mod2)
```



### logistic regression model

```{r}
glm_model <- acled %>%
  mutate(inter_type = fct_relevel(inter_type, "sole protester action"),
         event_type = fct_relevel(event_type, "Protests"),
         admin1 = fct_relevel(admin1, "Yangon")) %>%
  filter(year == 2021) %>%
  glm(has_fatalities ~ inter_type, data = .)

glm_model %>% 
  tidy() %>% 
  mutate(term = str_remove_all(term, c("sub_event_type|event_type|inter_type")),
         term = substr(term, 0, 45)) %>% 
  # mutate(term = recode(term, "(Intercept)" = "Protests")) %>% 
  # filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  arrange(desc(estimate)) %>% head(20) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_point()

```

```{r}

acled %>% filter(inter_type == "military versus military" & year == 2021) %>% pull(notes)
```


```{r}
acled_words %>% 
  filter(word %out% c("township", "district", "myanmar", "region", "village")) %>%
  group_by(word) %>% 
  summarise(number = n(), 
            events = n_distinct(data_id),
            fatalities = sum(fatalities)) %>% 
  arrange(desc(fatalities)) %>%  
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 100)
```

```{r}
acled %>%  
  # filter(fatalities == 0) %>% 
  group_by(event_type, sub_event_type, inter_type) %>% 
  summarise(count = n(), 
            fatalities = sum(fatalities)) %>% 
  mutate(per_event = fatalities / count) %>% 
  arrange(desc(count))

acled %>%  
  filter(fatalities > 0) %>% 
  group_by(event_type, sub_event_type, inter_type) %>% 
  summarise(count = n(), 
            fatalities = sum(fatalities)) %>% 
  mutate(per_event = fatalities / count) %>% 
  arrange(desc(count))

actors %>% filter(inter1 == "political_militias" & year == 2021) %>% count(actor_simple, sort = TRUE)
```


```{r}
acled %>% 
  filter(year == 2021) %>% 
  filter(sub_event_type != "Peaceful protests") %>% 
  group_by(admin1, admin3, event_type) %>% 
  summarise(count = n()) %>% 
  mutate(sum = sum(count)) %>% 
  ungroup() %>% 
  mutate(admin3 = fct_reorder(admin3, sum, .desc = TRUE)) %>% 
  distinct(admin1, admin3, sum) %>% 
  mutate(pc_total = round(sum / sum(sum) * 100, digits = 2)) %>% 
  arrange(desc(pc_total))
```

### side by side plots for fatalities and event type
```{r}
acled %>% 
  filter(year == 2021) %>%  
  mutate(inter_type = fct_relevel(inter_type, "sole protester action"),
         event_type = fct_relevel(event_type, "Protests"),
         admin1 = fct_relevel(admin1, "Yangon")) %>%
  lm(fatalities ~ admin1, data = .) %>% # anova() %>% tidy() %>% mutate(sumsq / sum(sumsq))
  tidy(conf.int = TRUE) %>% 
  # mutate(term = substr(term, 0, 45)) %>% 
  mutate(term = str_remove_all(term, "admin1"),
         term = recode(term, "(Intercept)" = "Yangon")) %>% 
  # filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high)) + 
  
actors %>% 
  filter(year == 2021) %>%  
  mutate(inter_type = fct_relevel(inter_type, "sole protester action"),
         event_type = fct_relevel(event_type, "Protests"),
         actor_simple = fct_relevel(fct_lump(actor_simple, 10), "Protesters (Myanmar)"),
         admin1 = fct_relevel(admin1, "Yangon")) %>%
  lm(fatalities ~ actor_simple, data = .) %>% # anova() %>% tidy() %>% mutate(sumsq / sum(sumsq))
  tidy(conf.int = TRUE) %>% 
  # mutate(term = substr(term, 0, 45)) %>% 
  mutate(term = str_remove_all(term, "actor_simple"),
         term = recode(term, "(Intercept)" = "Protesters (Myanmar)")) %>% 
  # filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high))
  
acled %>% 
  filter(year == 2021) %>%  
  mutate(inter_type = fct_relevel(inter_type, "sole protester action"),
         event_type = fct_relevel(event_type, "Protests"),
         admin1 = fct_relevel(admin1, "Yangon")) %>%
  lm(fatalities ~ event_type, data = .) %>% # anova() %>% tidy() %>% mutate(sumsq / sum(sumsq))
  tidy(conf.int = TRUE) %>% 
  # mutate(term = substr(term, 0, 45)) %>% 
  mutate(term = str_remove_all(term, "event_type"),
         term = recode(term, "(Intercept)" = "Protests")) %>% 
  # filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high))

actors %>% count(actor_simple, sort = TRUE)
```


```{r}
acled %>% 
  filter(year == 2021) %>%  
  filter(fatalities != 0) %>% 
  mutate(inter_type = fct_relevel(inter_type, "sole protester action"),
         event_type = fct_relevel(event_type, "Protests")) %>%
  lm(fatalities ~ event_type + inter_type + admin1, data = .) %>% 
  tidy(conf.int = TRUE) %>% 
  # mutate(term = substr(term, 0, 45)) %>% 
  mutate(term = recode(term, "(Intercept)" = "eventypeProtests")) %>% 
  # filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  anova() %>%
  mutate(sumsq / sum(sumsq))
```


```{r}


model2 <- actors %>% 
  filter

model %>% 
  tidy(conf.int = TRUE) %>% 
  mutate(term = substr(term, 0, 45)) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high))

acled %>% filter(year == 2021) %>% count(event_type, wt = fatalities)
glimpse(acled)
acled %>% filter(year == 2021) %>%  count(inter_type, sort = TRUE)
```

```{r}
anova(model) %>% 
  tidy() %>% 
  mutate(share = sumsq / sum(sumsq))
```


```{r}
model2 <- actors %>% 
  filter

model %>% 
  tidy(conf.int = TRUE) %>% 
  mutate(term = substr(term, 0, 45)) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high))

glimpse(acled)
```


```{r}
tree1 <- actors %>% 
  filter(year == 2021) %>% 
  rpart(fatalities ~ admin1 + inter1 + event_type, data = .)

fancyRpartPlot(tree1, digits = 3, sub = "", palettes = "Blues")
```


```{r}
acled %>% 
  filter(!is.na(event_type) & year < 2022) %>%
  mutate(year = round(year)) %>% 
  group_by(year, event_type) %>%
  summarise(fatalities = sum(fatalities), .groups = "drop") %>%
  ggplot(aes(year, fatalities, fill = event_type, group = event_type)) + 
  # geom_line(size = 1) + 
  geom_col() +
  geom_text(aes(label = comma(stat(y), accuracy = 1), group = year), stat = "summary", fun = sum, vjust = -0.7, size = 3) +
  scale_x_continuous(breaks = seq(2010, 2021, by = 1)) + 
  scale_y_continuous(labels = comma, limits = c(0, 12500)) +
  theme(axis.text.x = element_text(size = 9), 
        axis.text.y = element_text(size = 9), 
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        plot.caption = element_text(hjust = 0.5)) +
  labs(x = "", 
       y = "Number of conflict-related fatalities",
       title = "Fatalities by conflict event type, 2010-2021", 
       caption = "Data source: Armed Conflict Location & Event Data Project (ACLED); acleddata.com")
```

```{r}
acled %>%  
  filter(year == 2021) %>% 
  mutate(month = lubridate::month(event_date, label = TRUE)) %>% 
  group_by(month, event_type) %>% 
  summarise(count = n()) %>%
  mutate(month = fct_rev(month)) %>% 
  ggplot(aes(x = count, y = month, fill = stat(x))) + 
  geom_density_ridges_gradient() +
  scale_fill_viridis(option = "C") + 
  facet_wrap(~event_type)

acled %>%  
  filter(year == 2021) %>% 
  mutate(month = lubridate::month(event_date, label = TRUE)) %>% 
  group_by(month, event_type) %>% 
  summarise(count = n()) %>%
 #  mutate(month = fct_rev(month)) %>% 
  ggplot(aes(x = month, y = count, group = event_type, colour = event_type)) + 
  geom_smooth(se = FALSE) +
  facet_wrap(~event_type, scales = "free_y") + 
  labs(x = "",
       y = "Number of events", 
       title = "Progression of 2021 conflict events, by type",
       subtitle = "Data source: Armed Conflict Location & Event Data Project (ACLED); acleddata.com") + 
  theme(legend.position = "none")
  
```

### mine action

```{r}
acled_words_mine <- acled %>% 
  filter(year == 2021) %>% 
  filter(event_type == "Explosions/Remote violence") %>% 
  select(data_id, notes) %>% 
  unnest_tokens(word, notes) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(str_detect(word, "[a-z]")) %>% 
  left_join(acled %>% 
              select(data_id, admin3_pcode, event_type, fatalities, inter_type), by = "data_id")
```

```{r}
mine_network_graph <- acled_words_mine %>%  
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded",
                      "dvb", "aapp", "total", "irrawaddy", "rfa", "tract")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 20) %>% 
  pairwise_cor(word, data_id, sort = TRUE) %>% 
  filter(correlation >= 0.2) %>% 
  igraph::graph_from_data_frame() %>% 
  ggraph(layout = "fr") + 
  geom_edge_link(aes(alpha = correlation), colour = "blue") + 
  scale_alpha_continuous(range = c(0.1, 0.4)) +
  geom_node_point(colour = "blue", alpha = 0.3) +
  geom_node_text(aes(label = name), size = 3) + 
  theme(legend.position = "none") + 
  labs(title = "Network graph of words in descriptions of 2021 incidents of explosions and remote violence in Myanmar",
       subtitle = "Data source: Armed Conflict Location & Event Data Project (ACLED); acleddata.com")

ggsave("mine_network_graph.png", mine_network_graph, width = 42.0, height = 29.7, units = "cm", dpi = 300)

```

```{r dt-pairwise-words}
acled_words_mine %>%  
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded",
                      "dvb", "aapp", "rfa", "irrawaddy")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 50) %>% 
  pairwise_cor(word, data_id, sort = TRUE) %>%
  rename(word = item1, match = item2) %>% 
  group_by(word) %>% 
  top_n(correlation, n = 20) %>% 
  datatable(filter = list(position = "top", clear = FALSE), 
            options = list(pageLength = 10, scrollX = TRUE,
                           search = list(regex = TRUE)
  #                         
  #                         ,
  #                                         initComplete = htmlwidgets::JS(
  #        "function(settings, json) {",
  #        paste0("$(this.api().table().container()).css({'font-size': '", "8.5pt", "'});"),
  #        "}")
       ),
  caption = htmltools::tags$caption(style = 'caption-side: top; 
                                    text-align: center; 
                                    color:black; font-size:130% ;',
                                    "Pairwise correlations in conflict event descriptions of incidents of explosions and remote violence")
     ) %>% 
  formatRound(c("correlation"), digits = 3)

```

### fatalities

```{r}
# this is a little more helpful
acled_words %>%
  # filter(sub_event_type != "Peaceful protest") %>% 
  filter(word %out% c("fatality", "coded", "death", "village", "township", "district", "villages",
                      "town", "tract", "fatalities", "dvb", "aapp", "total", "irrawaddy", "rfa", "died",
                      "killing", "killed", "dead", "event", "events", "casualty", "casualties",
                      "size", "code", "report", "myanmar","coded")) %>% 
  mutate(has_fatalities = ifelse(fatalities > 0, "yes", "no")) %>% 
  count(has_fatalities, word) %>% 
  bind_log_odds(has_fatalities, word, n) %>% 
  group_by(has_fatalities) %>% 
  top_n(50, log_odds_weighted) %>% 
  ungroup() %>% 
  mutate(word = reorder_within(word, log_odds_weighted, has_fatalities)) %>% 
  ggplot(aes(x = log_odds_weighted, y = word)) + 
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ has_fatalities, scales = "free")

acled_words %>% count(fatalities)

# histogram fatalities 
acled %>% 
  filter(year == 2021) %>% 
  count(fatalities) %>% 
  ggplot(aes(x = fatalities, y = n)) +
  geom_col() + 
  scale_y_log10() 

townships

# ayeyarwaddy keeps on showing up because of the ayeyarwady river
acled %>% filter(year == 2021) %>% 
  filter(admin1 == "Sagaing") %>% 
  filter(str_detect(notes, "Ayeyarwady|ayeyarwady")) %>% 
  pull(notes)

acled %>% filter(year == 2021) %>% count(fatalities)

```


```{r}
acled_words %>% 
  filter(sub_event_type != "Peaceful protest") %>% 
  mutate(fatalities_bin = case_when(fatalities == 0 ~ "0", 
                                    fatalities == 1 ~ "1", 
                                    fatalities > 1 & fatalities < 6 ~ "2-5", 
                                    fatalities > 5 & fatalities < 11 ~ "5-10", 
                                    fatalities > 10 & fatalities < 21 ~ "11-20", 
                                    fatalities > 20 & fatalities < 31 ~ "21-30", 
                                    fatalities > 30 & fatalities < 51 ~ "31-50",
                                    fatalities > 50 ~ "51-88")) %>% 
  mutate(fatalities_bin = fct_relevel(fatalities_bin, c("0", "1", "2-5", "5-10", "11-20", "21-30", "31-50", "51-99", ">=100"))) %>% 
  filter(word %out% c("fatality", "coded", "death", "village", "township", "district", "villages",
                      "town", "tract", "fatalities", "dvb", "aapp", "total", "irrawaddy", "rfa", "died",
                      "killing", "killed", "dead", "event", "events", "casualty", "casualties",
                      "size", "code", "report", "myanmar","coded")) %>% 
  count(fatalities_bin, word) %>% 
  bind_log_odds(fatalities_bin, word, n) %>% 
  group_by(fatalities_bin) %>% 
  top_n(20, log_odds_weighted) %>% 
  ungroup() %>% 
  mutate(word = reorder_within(word, log_odds_weighted, fatalities_bin)) %>% 
  ggplot(aes(x = log_odds_weighted, y = word)) + 
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ fatalities_bin, scales = "free")

  
```

```{r}

acled_words %>%
  # filter(sub_event_type != "Peaceful protest") %>% 
  filter(word %out% c("fatality", "coded", "death", "village", "township", "district", "villages",
                      "town", "tract", "fatalities", "dvb", "aapp", "total", "irrawaddy", "rfa", "died",
                      "killing", "killed", "dead", "event", "events", "casualty", "casualties",
                      "size", "code", "report", "myanmar","coded")) %>% 
  mutate(has_fatalities = ifelse(fatalities > 0, "yes", "no")) %>% 
  count(has_fatalities, word) %>% 
  bind_log_odds(has_fatalities, word, n) %>% 
  group_by(has_fatalities) %>% 
  top_n(50, log_odds_weighted) %>% 
  ungroup() %>% 
  mutate(word = reorder_within(word, log_odds_weighted, has_fatalities)) %>% 
  ggplot(aes(x = log_odds_weighted, y = word)) + 
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ has_fatalities, scales = "free")

acled_words %>%
  anti_join(townships %>% 
              mutate(word = tolower(township_name)) %>% 
              select(word), by = "word") %>% 
  count(admin1, word) %>% 
  bind_tf_idf(word, admin1, n) %>% 
  group_by(admin1) %>% 
  top_n(tf_idf, n = 5) %>% 
  ungroup() %>% 
  mutate(word = reorder_within(word, tf_idf, admin1)) %>% 
  ggplot(aes(x = tf_idf, y = word)) + 
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ admin1, scales = "free")

# log odds here is not very helpful; tf_idf is also not very helpful 
acled_words %>%
  left_join(townships %>% select(state_name, admin3_pcode), by = "admin3_pcode") %>% 
  anti_join(townships %>% 
              mutate(word = tolower(township_name)) %>%
              select(word), by = "word") %>% 
  anti_join(townships %>% select(state_name) %>% 
              mutate(word = tolower(state_name)), by = "word") %>% 
  count(state_name, word) %>% 
  bind_log_odds(state_name, word, n) %>% 
  group_by(state_name) %>% 
  top_n(10, log_odds_weighted) %>% 
  ungroup() %>%
  ggplot(aes(x = log_odds_weighted, y = reorder_within(word, log_odds_weighted, state_name))) +
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ state_name, scales = "free_y")


```

### effects on liveihoods

```{r}
acled_words %>% 
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded",
                      "dvb", "aapp", "total", "irrawaddy", "rfa", "tract", "kic", "voa", "bbc")) %>% 
  distinct(data_id, word, fatalities) %>% 
  group_by(word) %>% 
  summarise(mean_fatalities = mean(fatalities),
            n = n()) %>% 
  filter(n >= 5) %>% 
  arrange(desc(mean_fatalities))

acled_words %>%  
  filter(word %out% c("township", "district", "myanmar", "region", "village", "town", "size", "report", "code", "coded",
                      "dvb", "aapp", "total", "irrawaddy", "rfa", "tract", "kic", "voa")) %>% 
  distinct(data_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 5) %>% 
  pairwise_cor(word, data_id, sort = TRUE) %>% 
  filter(correlation >= 0.2)

acled %>% filter(year == 2021) %>% 
  filter(str_detect(notes, "nationals")) %>% 
  pull(notes)

actors %>% filter(str_detect(actor1, "KIC"))

actors %>% count(actor1)

# this is interesting -- can you see if there is a pattern to the looting?
acled %>% filter(year == 2021) %>% 
  filter(str_detect(notes, "railway")) %>% 
  sample_n(10) %>% 
  pull(notes)

acled %>%  filter(year == 2021 & admin1 == "Yangon") %>% 
  top_n(20, wt = fatalities) %>% 
  pull(notes)
```

```{r}
# convoys, roads
acled %>% filter(year == 2021) %>% 
  filter(sub_event_type %out% c("Peaceful protest", "Change to group/activity")) %>% 
  filter(str_detect(notes,"road|convoy| car|vehicle|truck|business|Business|Shop|shop|loot|Loot|mine|highway|bomb|street|confiscated|barricade|factory|neighbourhood|ward")) %>% 
  mutate(sub_event_type = fct_lump(sub_event_type, 6)) %>% 
  right_join(pcode3_shape, by = "admin3_pcode") %>% 
  st_as_sf() %>% 
  filter(!is.na(sub_event_type)) %>% 
  ggplot() +
  geom_sf(alpha = 0, size = 0.1) +
  geom_point(aes(x = longitude, y = latitude, colour = sub_event_type, size = fatalities), alpha = 0.7) +
  scale_colour_manual(values = c("#D95F02", "#7570B3", "#1B9E77", "#E7298A", "#E6AB02", "#66A61E", "#666666", "#A6761D")) +
  scale_size_continuous(range = c(0.5, 3)) +
  geom_sf(data = pcode1_shape, alpha = 0, colour = "black", size = 0.5) +
  theme_void() +
  guides(colour = guide_legend(override.aes = list(size = 5))) +
  labs(title = "2021 Conflict events related to supply disruptions",
       subtitle = "Events related to transport infrastructure and property destruction/looting",
       caption = "Data source: ACLED: acleddata.com") + 
  theme(plot.background = element_rect(fill = "white", colour = NA),
        plot.caption = element_text(hjust = 0.5))


```

```{r}
# just ignore this whole chunk -- this was for the data sharing protocols 

fsc %>% 
  mutate(partner_code = case_when(reporting_organization %in% c("ACTED", "AVSI", "Danish Refugee Council") ~ "org4478",
                                  reporting_organization %in% c("ACTED", "Cordaid", "FAO") ~ "org0145",
                                  reporting_organization %in% c("Mercy Corps", "Oxfam", "Karuna Mission Social Solidarity") ~ "org2091",
                                  reporting_organization %in% c("Norwegian Refugee Council", "Trocaire") ~ "org0763",
                                  reporting_organization %in% c("Save the Children", "Helvetas", "Action Contre la Faim") ~ "org9963",
                                  TRUE ~ NA_character_)) %>%
  mutate(activity2 = case_when(activity == "Cash for Work / Food for Assets" ~ "Shelter kits", 
                              activity == "Provide monthly cash-based transfers" ~ "Hygiene kits", 
                              activity == "Provide technical training" ~ "Education kits",
                              activity == "Provide crops & vegetable kits" ~ "Multi-purpose cash",
                              TRUE ~ NA_character_)) %>% 
  filter(!is.na(partner_code) & !is.na(activity2)) %>% 
  filter(unique_beneficiaries == "Yes") %>% 
  ggplot(aes(x = partner_code, y = beneficiaries, fill = activity2)) + 
  geom_col() +
  scale_fill_brewer(palette = "Accent") +
  scale_y_continuous(labels = comma) +
  labs(fill = "activity", 
       title = "Beneficiaries reached by partner")

ggsave(filename = "./example_partner_tokens.png", dpi = 300, height = 4, width = 7, units = "in")
  
  
```

